apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  # echo -n postgres | base64
  postgres-user: cG9zdGdyZXM=
  postgres-password: YWRtaW5Qb3N0Z3Jlcw==
  postgres-db: bm90X2FuX2Vib29r